title: Tractorbeam
url: "https://tractorbeam.me"
permalink: pretty
favicon: /images/favicon.png
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - INDEX.md
remote_theme: chrisrhymes/bulma-clean-theme
exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ansible/
  - ansible-hosts
  - ansible.cfg

markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      hide_hero: true
      hide_footer: true